import "./globals.css";
import { Inter } from "next/font/google";
import Head from "next/head";
import {Metadata} from "next";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Odemakinde Elisha",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <Head>
            <link rel='icon' href='/favicon.ico'/>
        </Head>
        <body className={inter.className}>{children}</body>
        </html>
    );
}