import './globals.css'
import { Inter } from 'next/font/google'
import Head from "next/head";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <Head>
      <link rel="icon" href="https://st4.depositphotos.com/6903990/27898/i/450/depositphotos_278981062-stock-photo-beautiful-young-woman-clean-fresh.jpg" />fff
    </Head>
      <body className={inter.className}>
      {/*<Head>*/}
      {/*  <link rel="icon" href="./favicon.png" />*/}
      {/*</Head>*/}
      {children}
      </body>
    </html>
  )
}
